### ISSUE TITLE
Add markdown support for conversation view 

### ISSUE THREAD

**Issue by adamsilverstein** [adamsilverstein/wp-performance-wizard#19]
* Gemini Agent responses use markdown, it would be nice to display that correctly

**Comment by westonruter** [comment]
Meaning to render it as HTML instead?

**Comment by adamsilverstein** [comment]
Right, so the user would see a formatted response. Something like [this](https://github.com/jcubic/jquery.terminal/wiki/Formatting-and-Syntax-Highlighting#markdown-parser).
